// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZRAb--MSpu-8JaHrDjLVq4TyMqVds5aA',
    appId: '1:997299042643:web:504f89dd3bcc57c98d09a6',
    messagingSenderId: '997299042643',
    projectId: 'banco-de-dados-251fe',
    authDomain: 'banco-de-dados-251fe.firebaseapp.com',
    storageBucket: 'banco-de-dados-251fe.appspot.com',
    measurementId: 'G-SCE8V6QC3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFvT9SxEvBghQbKIrUsg8YCPf_hvvMCwI',
    appId: '1:997299042643:android:379c467a7c807ddb8d09a6',
    messagingSenderId: '997299042643',
    projectId: 'banco-de-dados-251fe',
    storageBucket: 'banco-de-dados-251fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL1tMpIw5xOSd_RhrI6bnhzrdwnq_H0pw',
    appId: '1:997299042643:ios:b376594d2f840aff8d09a6',
    messagingSenderId: '997299042643',
    projectId: 'banco-de-dados-251fe',
    storageBucket: 'banco-de-dados-251fe.appspot.com',
    iosClientId: '997299042643-iuuq7nmlouflq91cje7cv87p3136oki9.apps.googleusercontent.com',
    iosBundleId: 'br.com.paulofelix.flutterFirebaseTeste',
  );
}
